# Generated by Django 4.1.7 on 2023-03-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measures',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
