# Generated by Django 4.1.7 on 2023-03-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_measures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='product',
            name='measures',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
