# Generated by Django 4.1.7 on 2023-03-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_product_measures'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measures',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
