# Generated by Django 4.1.7 on 2023-02-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(default='example@email.com', max_length=254)),
                ('worth_invoice', models.IntegerField(default=0)),
                ('date_invoice', models.DateTimeField(verbose_name=' date invoice ')),
                ('status_payment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_product', models.IntegerField(default=0)),
                ('worth_sale', models.IntegerField(default=0)),
                ('id_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.invoice')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
